version: '3.8'
services:
  #https://github.com/khezen/compose-postgres
  db:
    container_name: {{cookicuter.project_name}}_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: {{cookicuter.postgres_user}}
      POSTGRES_PASSWORD: {{cookicuter.postgres_password}}
      POSTGRES_DB: {{cookicuter.postgres_database_name}}
    ports:
      - "5432:5432"

  pgadmin:
    container_name: {{cookicuter.project_name}}_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  # -----------------------------------------------------

  redis:
    image: redis
    container_name: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes